/*
 * Port_PBcfg.c
 *
 *  Created on: 12 Feb 2022
 *      Author: kirol
 */

#include "Port.h"
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (1U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Dio_Init API */
const Port_ConfigType Port_Configuration = {
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		LED,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		CHANNEL_DEFAULT,
		SWITCH,



				         };
